name: PyTorch Tutorials

on:
  push:
    paths:
      - 'cleverhans/torch/**/*'
      - 'tutorials/torch/**/*'

  pull_request:
    paths:
      - 'cleverhans/torch/**/*'
      - 'tutorials/torch/**/*'

jobs:

  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
              --cloud aws \
              --cloud-region us-east \
              --cloud-type=p2.xlarge \
              --labels=cml-runner
  model-training:
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-runner]
    container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Run tutorial
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -e "."
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-pytorch.txt
          pip install -r requirements/requirements-dev.txt
          pip install -r requirements/requirements-gpu.txt

          find tutorials/torch/ -name '*.py' | while read f
          do
              python $f
              if [ $? -ne 0 ]
              then
                  exit 1
              fi
          done
